// <auto-generated />
using System;
using DAL_QLBH.Databasecontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL_QLBH.Migrations
{
    [DbContext(typeof(Database_Poly))]
    partial class Database_PolyModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DAL_QLBH.entities.Hang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Dgiaban")
                        .HasColumnType("real");

                    b.Property<float>("Dgianhap")
                        .HasColumnType("real");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Hinhanh")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasMaxLength(28)
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.HasKey("MaHang");

                    b.HasIndex("MaNV");

                    b.ToTable("Hang");
                });

            modelBuilder.Entity("DAL_QLBH.entities.KhachHang", b =>
                {
                    b.Property<Guid>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.Property<int>("MaNV")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("Phai")
                        .HasColumnType("int");

                    b.Property<string>("SDtKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DAL_QLBH.entities.Lichsu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lucra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Lucvao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tinhtrang")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("LichSu");
                });

            modelBuilder.Entity("DAL_QLBH.entities.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tinhtrang")
                        .HasColumnType("bit");

                    b.Property<int>("vaitro")
                        .HasColumnType("int");

                    b.HasKey("MaNV");

                    b.ToTable("Nhanvien");
                });

            modelBuilder.Entity("DAL_QLBH.entities.Hang", b =>
                {
                    b.HasOne("DAL_QLBH.entities.NhanVien", "NhanVien")
                        .WithMany("Hangs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL_QLBH.entities.KhachHang", b =>
                {
                    b.HasOne("DAL_QLBH.entities.NhanVien", "NhanVien")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL_QLBH.entities.NhanVien", b =>
                {
                    b.Navigation("Hangs");

                    b.Navigation("KhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
